#!/bin/bash

filelist="dz1.c part2"
foldertmp="tmp/guesanumber"
folderrelease="release"
filearchive="guesanumber.tar.gz"
tarswitches="zcf"

mkdir -p $foldertmp

for file in $filelist
do
    cp $file $foldertmp
done

tar -$tarswitches $filearchive $foldertmp

mkdir -p $folderrelease
cp $filearchive $folderrelease
