#! /bin/bash 

ARCH=guesanumber.tar.gz
TEMP=/tmp/guesanumber
DIR=release

if ! [ -d $TEMP ]
	then
		mkdir $TEMP
fi

cp *.c $TEMP

tar -cvzf  $ARCH $TEMP

if ! [ -d $DIR ]
        then
                mkdir $DIR
fi

mv $ARCH $DIR

rm -r $TEMP

