#! /bin/sh

#Create folders tmp/guess_a_number/
mkdir -p tmp/guess_a_number

#Find files with extension ".c" or ".h" and copy to folder with entered name
ls *.c *.h | xargs cp -t tmp/guess_a_number

#Zip the folders
tar -cvzf guess_a_number.tar.gz tmp/guess_a_number

#Create folders release 
if [ ! -d release ] 
then
	mkdir release	
fi
cp guess_a_number.tar.gz ./release
#Copy to folder zip archive


#Remove tmp folder
rm -R tmp

#Remove ip archive
rm guess_a_number.tar.gz


